version: '3.8'
services:

  cache_p1:
    image: redis:latest  
    container_name: cache_p1
    
    ports:
      - "6380:6380"  
    

  cache_p2:
    image: redis:latest
    
    container_name: cache_p2
    ports:
      - "6381:6381"
    

  cache_p3:
    image: redis:latest
     
    container_name: cache_p3
    ports:
      - "6382:6382"
    

   
  postgres:
    build: ./postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: base
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: server
    ports:
      - "50051:50051"
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
      - ./server/ss.proto:/app/proto/ss.proto
  api:
    build: ./cliente
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./src:/app/src
      - ./cliente/ss.proto:/app/proto/ss.proto

volumes:
  postgres-data:
