version: '3.8'
services:

  cache-master:
    image: redis:latest
    container_name: cache-master
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  redis-rep1:
    image: redis:latest
    container_name: redis-rep1
    ports:
      - "6380:6379"
    environment:
      - REDIS_REPLICATION_MODE=replica
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT=6379
    depends_on:
      - cache-master
    command: redis-server --replicaof redis-master 6379

    redis-rep2:
      image: redis:latest
      container_name: cache-rep2
      ports:
        - "6381:6379"
      environment:
        - REDIS_REPLICATION_MODE=replica
        - REDIS_MASTER_HOST=redis-master
        - REDIS_MASTER_PORT=6379
      depends_on:
        - redis-master
      command: redis-server --replicaof redis-master 6379

  postgres:
    build: ./postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: base
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: server
    ports:
      - "50051:50051"
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
      - ./server/ss.proto:/app/proto/ss.proto
  api:
    build: ./cliente
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./src:/app/src
      - ./cliente/ss.proto:/app/proto/ss.proto

volumes:
  postgres-data:
